server:
  port: 8085

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:demo_db
    username: sa
    password: admin
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
